### ISSUE TITLE
my app crash!!

### ISSUE THREAD

**Issue by git-xyz** [AlbertBrand/react-native-android-tablayout#31]
react native 0.36
compileSdkVersion 23
buildToolsVersion "23.0.1"

nothing else 

no errors

**Comment by janoschpizza** [comment]
Same problem here with same RN / Android SDK versions.

As soon as I touch another Tab the app crashes to home screen with message "Unfortunately App has stopped."

**Comment by piotrpoz** [comment]
Same here. 
RN: 0.37
targetSDK: 23

Here is a logcat log:

```
--------- beginning of crash
11-14 17:55:14.834 E/AndroidRuntime( 4291): FATAL EXCEPTION: main
11-14 17:55:14.834 E/AndroidRuntime( 4291): Process: com.test, PID: 4291
11-14 17:55:14.834 E/AndroidRuntime( 4291): java.lang.NoSuchMethodError: No direct method <init>(IJ)V in class Lcom/facebook/react/uimanager/events/Event; or its super classes (declaration of 'com.facebook.react.uimanager.events.Event' appears in /data/app/com.test-2/base.apk)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at com.xebia.reactnative.TabSelectedEvent.<init>(TabSelectedEvent.java:14)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at com.xebia.reactnative.TabLayoutManager$TabLayoutOnTabSelectedListener.onTabSelected(TabLayoutManager.java:152)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.support.design.widget.TabLayout.selectTab(TabLayout.java:837)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.support.design.widget.TabLayout.selectTab(TabLayout.java:809)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1077)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.support.design.widget.TabLayout$1.onClick(TabLayout.java:643)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.view.View.performClick(View.java:5198)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.view.View$PerformClick.run(View.java:21147)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.os.Handler.handleCallback(Handler.java:739)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.os.Looper.loop(Looper.java:148)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at java.lang.reflect.Method.invoke(Native Method)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-14 17:55:14.834 E/AndroidRuntime( 4291):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 17:55:14.835 W/ActivityManager( 1557):   Force finishing activity com.test/.MainActivity
```

**Comment by qntnrbns** [comment]
What version of this package are you using??

**Comment by piotrpoz** [comment]
@thebicycle2 it is 0.3.0.

**Comment by janoschpizza** [comment]
@thebicycle2 0.3.0

**Comment by qntnrbns** [comment]
I haven't had the time to test it myself yet, but the HEAD of master is not the same package that npm is currently distributing. @AlbertBrand pulled in a commit cd8cd152870d33818ddf97976da8872926a07b20 that fixed a bug in TabSelectedEvent. Try pulling that package using the github url instead, and see what happens.

**Comment by piotrpoz** [comment]
@thebicycle2 This was brilliant idea. Seems master's HEAD is free of this issue. Would be great to tag/release this one as bug seems to be critical.

**Comment by PARAGJYOTI** [comment]
App crashes . Please please fix this . This is one of the most useful libs i found on react-native .
